/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as SystemLogsRouteImport } from './routes/system-logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as RecruiterApplicationsRouteImport } from './routes/recruiter-applications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterApplicationsRoute = RecruiterApplicationsRouteImport.update({
  id: '/recruiter-applications',
  path: '/recruiter-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRoute
  '/hospitals': typeof HospitalsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/recruiter-applications': typeof RecruiterApplicationsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/system-logs': typeof SystemLogsRoute
  '/verifications': typeof VerificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRoute
  '/hospitals': typeof HospitalsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/recruiter-applications': typeof RecruiterApplicationsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/system-logs': typeof SystemLogsRoute
  '/verifications': typeof VerificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/candidates': typeof CandidatesRoute
  '/hospitals': typeof HospitalsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/recruiter-applications': typeof RecruiterApplicationsRoute
  '/recruiters': typeof RecruitersRoute
  '/settings': typeof SettingsRoute
  '/system-logs': typeof SystemLogsRoute
  '/verifications': typeof VerificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/applications'
    | '/candidates'
    | '/hospitals'
    | '/jobs'
    | '/login'
    | '/recruiter-applications'
    | '/recruiters'
    | '/settings'
    | '/system-logs'
    | '/verifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/applications'
    | '/candidates'
    | '/hospitals'
    | '/jobs'
    | '/login'
    | '/recruiter-applications'
    | '/recruiters'
    | '/settings'
    | '/system-logs'
    | '/verifications'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/applications'
    | '/candidates'
    | '/hospitals'
    | '/jobs'
    | '/login'
    | '/recruiter-applications'
    | '/recruiters'
    | '/settings'
    | '/system-logs'
    | '/verifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CandidatesRoute: typeof CandidatesRoute
  HospitalsRoute: typeof HospitalsRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  RecruiterApplicationsRoute: typeof RecruiterApplicationsRoute
  RecruitersRoute: typeof RecruitersRoute
  SettingsRoute: typeof SettingsRoute
  SystemLogsRoute: typeof SystemLogsRoute
  VerificationsRoute: typeof VerificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-logs': {
      id: '/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-applications': {
      id: '/recruiter-applications'
      path: '/recruiter-applications'
      fullPath: '/recruiter-applications'
      preLoaderRoute: typeof RecruiterApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationsRoute: ApplicationsRoute,
  CandidatesRoute: CandidatesRoute,
  HospitalsRoute: HospitalsRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  RecruiterApplicationsRoute: RecruiterApplicationsRoute,
  RecruitersRoute: RecruitersRoute,
  SettingsRoute: SettingsRoute,
  SystemLogsRoute: SystemLogsRoute,
  VerificationsRoute: VerificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
