/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as CvPreviewRouteImport } from './routes/cv-preview'
import { Route as BuildCvRouteImport } from './routes/build-cv'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as ApplyJobIdIndexRouteImport } from './routes/apply.$jobId.index'
import { Route as ApplyJobIdUploadRouteImport } from './routes/apply.$jobId.upload'
import { Route as ApplyJobIdFormRouteImport } from './routes/apply.$jobId.form'

const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CvPreviewRoute = CvPreviewRouteImport.update({
  id: '/cv-preview',
  path: '/cv-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCvRoute = BuildCvRouteImport.update({
  id: '/build-cv',
  path: '/build-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdIndexRoute = ApplyJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyJobIdRoute,
} as any)
const ApplyJobIdUploadRoute = ApplyJobIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApplyJobIdRoute,
} as any)
const ApplyJobIdFormRoute = ApplyJobIdFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => ApplyJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/build-cv': typeof BuildCvRoute
  '/cv-preview': typeof CvPreviewRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/apply/$jobId': typeof ApplyJobIdRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/apply/$jobId/form': typeof ApplyJobIdFormRoute
  '/apply/$jobId/upload': typeof ApplyJobIdUploadRoute
  '/apply/$jobId/': typeof ApplyJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/build-cv': typeof BuildCvRoute
  '/cv-preview': typeof CvPreviewRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/apply/$jobId/form': typeof ApplyJobIdFormRoute
  '/apply/$jobId/upload': typeof ApplyJobIdUploadRoute
  '/apply/$jobId': typeof ApplyJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/build-cv': typeof BuildCvRoute
  '/cv-preview': typeof CvPreviewRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/apply/$jobId': typeof ApplyJobIdRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/apply/$jobId/form': typeof ApplyJobIdFormRoute
  '/apply/$jobId/upload': typeof ApplyJobIdUploadRoute
  '/apply/$jobId/': typeof ApplyJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/build-cv'
    | '/cv-preview'
    | '/messages'
    | '/profile'
    | '/saved-jobs'
    | '/apply/$jobId'
    | '/jobs/$jobId'
    | '/apply/$jobId/form'
    | '/apply/$jobId/upload'
    | '/apply/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/build-cv'
    | '/cv-preview'
    | '/messages'
    | '/profile'
    | '/saved-jobs'
    | '/jobs/$jobId'
    | '/apply/$jobId/form'
    | '/apply/$jobId/upload'
    | '/apply/$jobId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/build-cv'
    | '/cv-preview'
    | '/messages'
    | '/profile'
    | '/saved-jobs'
    | '/apply/$jobId'
    | '/jobs/$jobId'
    | '/apply/$jobId/form'
    | '/apply/$jobId/upload'
    | '/apply/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  BuildCvRoute: typeof BuildCvRoute
  CvPreviewRoute: typeof CvPreviewRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SavedJobsRoute: typeof SavedJobsRoute
  ApplyJobIdRoute: typeof ApplyJobIdRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-preview': {
      id: '/cv-preview'
      path: '/cv-preview'
      fullPath: '/cv-preview'
      preLoaderRoute: typeof CvPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-cv': {
      id: '/build-cv'
      path: '/build-cv'
      fullPath: '/build-cv'
      preLoaderRoute: typeof BuildCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId/': {
      id: '/apply/$jobId/'
      path: '/'
      fullPath: '/apply/$jobId/'
      preLoaderRoute: typeof ApplyJobIdIndexRouteImport
      parentRoute: typeof ApplyJobIdRoute
    }
    '/apply/$jobId/upload': {
      id: '/apply/$jobId/upload'
      path: '/upload'
      fullPath: '/apply/$jobId/upload'
      preLoaderRoute: typeof ApplyJobIdUploadRouteImport
      parentRoute: typeof ApplyJobIdRoute
    }
    '/apply/$jobId/form': {
      id: '/apply/$jobId/form'
      path: '/form'
      fullPath: '/apply/$jobId/form'
      preLoaderRoute: typeof ApplyJobIdFormRouteImport
      parentRoute: typeof ApplyJobIdRoute
    }
  }
}

interface ApplyJobIdRouteChildren {
  ApplyJobIdFormRoute: typeof ApplyJobIdFormRoute
  ApplyJobIdUploadRoute: typeof ApplyJobIdUploadRoute
  ApplyJobIdIndexRoute: typeof ApplyJobIdIndexRoute
}

const ApplyJobIdRouteChildren: ApplyJobIdRouteChildren = {
  ApplyJobIdFormRoute: ApplyJobIdFormRoute,
  ApplyJobIdUploadRoute: ApplyJobIdUploadRoute,
  ApplyJobIdIndexRoute: ApplyJobIdIndexRoute,
}

const ApplyJobIdRouteWithChildren = ApplyJobIdRoute._addFileChildren(
  ApplyJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  BuildCvRoute: BuildCvRoute,
  CvPreviewRoute: CvPreviewRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SavedJobsRoute: SavedJobsRoute,
  ApplyJobIdRoute: ApplyJobIdRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
